language: C

compiler:
  - gcc

addons:
  apt:
    sources:
    - sourceline: 'ppa:bitcoin/bitcoin'
    packages:
    - build-essential
    - libtool
    - autotools-dev
    - automake
    - pkg-config
    - libssl-dev
    - libevent-dev
    - bsdmainutils
    - python3
    - git
# BerkeleyDB
    - libboost-all-dev
    - software-properties-common
    - libdb4.8-dev
    - libdb4.8++-dev
# c-lightning
    - autoconf
    - automake
    - build-essential
    - git
    - libtool
    - libgmp-dev
    - libsqlite3-dev
    - python
    - python3
    - net-tools
    - libsodium-dev
    - libsodium-dev

before_install:
#  - sudo add-apt-repository -y ppa:bitcoin/bitcoin
  - sudo apt-get update -q
  - sudo apt-get upgrade -y
#  - sudo apt install -y libdb4.8-dev libdb4.8++-dev

install:
  - sudo ./install.sh

script:
  - true